# Generated by Django 4.2.5 on 2024-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericviews', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
